// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5839.FRC20185839.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5839.FRC20185839.Robot;

/**
 *
 */
public class CubeOut extends Command {

    public CubeOut() {

        requires(Robot.intaker);
        
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	Robot.intaker.SolenoidClose();
    	Robot.intaker.Intake();
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return !Robot.oi.joystickButton34.get();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.intaker.Stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
